# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81e5ca463da5bfaf7451affc352e6245d4122598f076eb40ca6a12d49eb162eb100aa016d9c5967f2fb9133ec4fbdadaddda17ba4ff0cb346d2f7b124a43a173

test:
  secret_key_base: 93927be49c1ed23b70b5f59248e5265dbb34b99951a159b527d2917d6e4f4845a1d4df6c15f817e71785b8f50a3c89fe47149a32a44aa95c11ee200e2f9942b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
